### ISSUE TITLE
Use an interface for Indexer or make it fully extendable

### ISSUE THREAD

**Issue by florentdestremau** [algolia/search-bundle#136]
While trying to make tests without hitting on an actual algolia api, I am sadly seeing that many classes are private, and there is no interface so absolutely no way to override and mock the bundle.

**Comment by julienbourdeau** [comment]
Hi @florentdestremau,

I'm releasing v3.0 of this bundle (very soon, [doc is already live](https://www.algolia.com/doc/api-client/symfony/getting-started/)) where I used Interface as much as possible. I hope you get to do everything you need, otherwise, just let me know.

Note that v3 is compatible with Symfony 3.4 and 4.0. I'll release also a last version of 2.x but it won't have radical change like this.

Any feedback on 3.0 is very welcome!

**Comment by florentdestremau** [comment]
hi ! 
Nice to know ! I'll try it out (but we kinda stopped using algolia for others reasons ^^' )
