### ISSUE TITLE
[3.0] Pagination problem

### ISSUE THREAD

**Issue by JacobDelcroix** [algolia/search-bundle#197]
Hi guys,

I'm having a problem when trying to implements a pagination system for my videos list.
First, I do a empty search to get all my videos (first 20)

```
$this->indexManager->rawSearch("", "my_indice", 1, 20, []);

array:12 [▼
  "hits" => array:20 [▶]
  "nbHits" => 7100
  "page" => 0
  "nbPages" => 50
  "hitsPerPage" => 20
  "processingTimeMS" => 3
  "facets" => array:5 [▶]
  "facets_stats" => array:4 [▶]
  "exhaustiveFacetsCount" => true
  "exhaustiveNbHits" => true
  "query" => ""
  "params" => "filters=status+%3D+0&facets=%5B%22video_quality%22%2C%22is_cycling%22%2C%22is_running%22%2C%22is_rowing%22%2C%22vehicle%22%5D&hitsPerPage=20&page=0&query="
]
```

As you can see I have 7000+ videos, so my pagination goes to 350+ pages.
But when trying to access page 51 and more I have this error:

> you can only fetch the 1000 hits for this query. You can extend the number of hits returned via the paginationLimitedTo index parameter or use the browse method. You can read our FAQ for more details about browsing: https://www.algolia.com/doc/faq/index-configuration/how-can-i-retrieve-all-the-records-in-my-index

Do you have any idea to solve this issue? I understand that Algolia can't give me more than 1000+ result but I only ask for 20 items (1000-1020). I also try the offset/length way but same error.

Thanks,
Jacob.

**Comment by tristanbes** [comment]
Hello,

you can import your settings from algolia, using the appropriate commmand from the bundle `php bin/console search:settings:backup`. 
Then, go in the imported settings `xxx.json` and change the line: 

`"paginationLimitedTo": 1000,` to the value you want, but you have to take care, it has a negative impact on performance.

More on this on the algolia documentation: https://www.algolia.com/doc/api-reference/api-parameters/paginationLimitedTo/

**Comment by JacobDelcroix** [comment]
Thanks for your reply,

So this is not a bug? Because like I said I only want to retrieve 20 items per page so Algolia don't need to return me more than 20 items... I juste want to paginate them.

That's strange that a search engine don't provide this kind a feature without losing performance...

**Comment by julienbourdeau** [comment]
Indeed Algolia is limited to 1000 results for pagination and can be changed via settings. Although, it's generally not recommended to change it since it has performance impact.

If you need to loop through all results (like to export them), I'd recommend you to use [`browse`](https://www.algolia.com/doc/api-reference/api-methods/browse/).

If you're displaying results on your site, I'd recommend to display something like "results 21-40 / 1000+" and stop pagination at 1000 results. I understand it might feel counter-natural but I'm not sure someone will ever browse 300 pages. We want to encourage people to search and use filters instead.

If I missed something, please provide some details about your integration so I can better help you.

**Comment by julienbourdeau** [comment]
@JacobDelcroix Please let me know if you need further details, I'll reopen this PR.
