### ISSUE TITLE
Count does not appear to take parameters into account

### ISSUE THREAD

**Issue by nmeirik** [algolia/search-bundle#259]
- Symfony version: 4.1.1
- Algolia Search Bundle version: 3.2.0
- Algolia Client Version: 1.27.0
- Language Version: ??

### Description
`$parameters` are not taken into account when passed to the `count()` method of the IndexManagager. As a result, the count returned is incorrect.

### Steps To Reproduce
```
$count = $indexManager->count($query, Entity::class, $parameters);
```

`Algolia\SearchBundle\IndexManager::count` accepts `$parameters` as its third parameter, but the variable is not used in the method.

**Comment by julienbourdeau** [comment]
Hi @nmeirik,
Thanks for reporting this issue, indeed the parameter is not passed to the Engine and because the interface doesn't define it, it would be a breaking change to add it.

I came up with this fix temporarily, until we release a next major version. Would you mind trying this PR? https://github.com/algolia/search-bundle/pull/260

**Comment by nmeirik** [comment]
Hi @julienbourdeau,

Thanks for addressing this so quickly.

> Would you mind trying this PR? 

How would I go about doing that? And what specifically are you looking for me to test?

**Comment by julienbourdeau** [comment]
When I test a PR, when it's small enough, I'd just copy/paste the modification in the `vendor` directory.

In this case, I don't think you need to test it, it's pretty obvious. I'll release it, you can update your dependency and if you still have issues, please keep us posted.
