### ISSUE TITLE
Bad Symfony Flex recipe installed

### ISSUE THREAD

**Issue by emulienfou** [algolia/search-bundle#262]
- Symfony version: **4.1.4**
- Algolia Search Bundle version: **3.3.2**
- Algolia Client Version: **1.27.0**

### Description
Bad recipe installed.

### Steps To Reproduce
1. Update the `composer.json` file manually, add:
```json
"algolia/algolia-search-bundle": "^3.3",
```
2. Execute the next command:
```bash
composer update
```
### Output
```
Package operations: 2 installs, 0 updates, 0 removal
- Installing algolia/algoliasearch-client-php (1.27.0): Loading from cache
- Installing algolia/algolia-search-bundle (3.3.2): Loading from cache

Symfony operations: 1 recipe (f2620db9b2a69f714b205b09c083e2f3)
  - Configuring algolia/algolia-search-bundle (>=2.2): From github.com/symfony/recipes-contrib:master
```

> The issue is Symfony Flex use the **2.2** version of the recipe instead of the **3.0**.

**Comment by nunomaduro** [comment]
@emulienfou Hey 👋

After checking the [documentation of symfony recipes]([github.com/symfony/recipes#creating-recipes](https://github.com/symfony/recipes#creating-recipes)):  _"They must follow the vendor/package/version/ directory structure, where version is the minimum version supported by the recipe."_

@julienbourdeau You have more experience them me on Symfony Applications, what do you think? 🧐

**Comment by julienbourdeau** [comment]
@emulienfou I think the issue is that you required `algolia/algolia-search-bundle`. When I release the 3.0 version I renamed the package to `algolia/search-bundle`.

If you look at the recipes, there is nothing for algolia-search-bundle > 3.0
https://github.com/symfony/recipes-contrib/tree/master/algolia

Thanks a lot for reporting this, I will see if I can add a symlink `algolia-search-bundle/3.0 -> search-bundle/3.0`. 👍 
In the meantime, can you confirm that requireing `search-bundle` will use the correct recipe?

**Comment by emulienfou** [comment]
Hello guys,
first off, this is a little confused for everyone I think.

In Packagist.org, you have the old package `algolia/algolia-search-bundle` and the new package `algolia/search-bundle` who provide the same versions (3.3.2 by example).
It would be logical to **abandoned** the old version on Packagist and refer to the new package name!
In this case, people won't use anymore the old package name like I did, when they came directly from Packagist.org.

Secondly, using `algolia/search-bundle` works perfectly.

**Comment by nunomaduro** [comment]
@emulienfou This issue has been fixed. Thanks!
